### ISSUE TITLE
LNMP如何配置Gitlab的反向代理和HTTPS - 一个球的博客

### ISSUE THREAD

**Issue by jw-12138** [jw-12138/jw-12138.github.io#8]
https://jw12138.com/#/post/202005-a01.html 

 Front-end Developer / Music Producer

**Comment by jw-12138** [comment]
这样配置会导致letsencrypt证书不正常续约，问题还在排查中...

**Comment by tsai12138** [comment]
```html
<test v-for="i in arr"></test>
```

**Comment by tsai12138** [comment]
```html
<test v-for="i in arr"></test>
```
```css
.gt-header-textarea{
            color:#ddd;
            background-color: lighten(@dark, 15%);
            &:hover{
                color:#ddd;
                background-color: lighten(@dark, 15%);
            }
        }
        .gt-comment-body{
            color:#ddd !important
        }
```
